### ISSUE TITLE
ActiveMocker deletes entire hard disk

### ISSUE THREAD

**Issue by nightscape** [zeisler/active_mocker#20] opened 2015-02-23 14:03 UTC
ActiveMocker has a very critical problem:
https://github.com/zeisler/active_mocker/blob/master/lib/active_mocker/generate.rb#L104
We can't yet reproduce how exactly this happened, but somehow in the above line ```Config.mock_dir``` was ```nil``` or ```""``` which caused ActiveMocker to delete everything it could under the root partition!

**Comment by nightscape** [comment] 2015-02-24 10:41
Ok, turns out that if you run this thing without Rails then ```Config.mock_dir``` keeps its default ```nil```:
https://github.com/zeisler/active_mocker/blob/master/lib/active_mocker/config.rb#L34

Wow, so scare, much danger :p

**Comment by zeisler** [comment] 2015-03-01 05:21
This is not good, I am sorry that this happened. I would of gotten to it sooner, but I am in the middle of a move and didn't see it. I will make a patch asap.

**Comment by zeisler** [comment] 2015-03-01 19:42
With these commit I have put in several guards to keep this from ever happening again. https://github.com/zeisler/active_mocker/commit/86fb8bd129342e113f6fd1f0b295c5053170cfec https://github.com/zeisler/active_mocker/commit/db728d0d32b3b94c45770216d4f269f8a93aa378

This has been fixed by raising an error if mock_dir is not set. Also, it will never delete any directories, only files that match `*_mock.rb`.

Releasing version 1.8.2 shortly. Due to the severity of this issue it highly recommended that everyone upgrade.

**Closed by zeisler** 2015-03-01 19:42 UTC

**Comment by zeisler** [comment] 2015-03-01 21:04
After testing this in a virtual machine I found it can only happen if you're running as root. So to make this happen you have to run as root and not have Rails in your gemfile. I would recommend only running as root when absolutely necessary as a general rule in Unix. Neverless the issue is fixed and will not happen no matter if your are running as root or not.

Repeatable Test Steps
DO NOT TRY ON YOUR PERSONAL COMPUTER!
```ruby
$ sudo irb
irb(main):002:0> require 'fileutils'
=> true
irb(main):003:0> FileUtils.rm_rf("#{nil}/")
```

**Comment by jmtoball** [comment] 2015-03-02 09:20
Although you can still delete all files that belong to you as non-root. At least that's what happened to me and what @nightscape described in this issue. Thank you for fixing this so quickly :-)

**Comment by zeisler** [comment] 2015-03-02 15:32
Again I apologize for this happening, it's a complete over sight in my part. Hopefully you had backups. 

If you find that ActiveMocker brings value to you consider contributing. There are places that need documentation, feature request, code clean up and optimizations that would all be welcome.
