### ISSUE TITLE
undefined method `colorize' for "superclass must be a Class (Module given)":String

### ISSUE THREAD

**Issue by markburns** [zeisler/active_mocker#65] opened 2016-05-04 02:26 UTC
On latest master we have the following exception when running `bundle exec rake active_mocker:build`. Which makes me think there is maybe not enough test coverage.

```
NoMethodError: undefined method `colorize' for "superclass must be a Class (Module given)":String
/Users/markburns/code/active_mocker/lib/active_mocker/display_errors.rb:36:in `block in display_errors'
/Users/markburns/code/active_mocker/lib/active_mocker/display_errors.rb:32:in `each'
/Users/markburns/code/active_mocker/lib/active_mocker/display_errors.rb:32:in `display_errors'
/Users/markburns/code/active_mocker/lib/active_mocker/generate.rb:26:in `call'
/Users/markburns/code/active_mocker/lib/active_mocker/public_methods.rb:31:in `create_mocks'
/Users/markburns/code/active_mocker/lib/active_mocker/task.rake:12:in `block (2 levels) in <top (required)>'
```

**Comment by zeisler** [comment] 2016-05-04 16:20
I am unable to reproduce this error

**Comment by markburns** [comment] 2016-05-04 17:53
Are you running bundle exec? Maybe using in a rails app that includes the colorized gem itself?

**Comment by zeisler** [comment] 2016-05-04 18:16
I am using `bundle exec` and was testing it with the [example_rails_app](https://github.com/zeisler/active_mocker/tree/master/example_rails_app)

**Comment by vshjxyz** [comment] 2016-05-05 12:43
hey guys, same error here using `ERROR_VERBOSITY=3 rake active_mocker:build`

**Comment by zeisler** [comment] 2016-05-05 22:47
Should be fixed with this merged PR https://github.com/zeisler/active_mocker/pull/67

**Closed by zeisler** 2016-05-05 22:47 UTC
